-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ui = {
		button = {
			long = {
				inviting = "rbxassetid://15646458962",
				placeholder = "rbxassetid://15646459028",
			},
		},
		icons = {
			["box-arrow-in-right"] = "rbxassetid://15646691259",
			["plus-lg"] = "rbxassetid://15646533091",
		},
	},
}