-- This file was @generated by Tarmac. It is not intended for manual editing.
return {
	ui = {
		button = {
			long = {
				inviting = "rbxassetid://15646458962",
				placeholder = "rbxassetid://15646459028",
			},
			thin = {
				placeholder = "rbxassetid://15647928801",
			},
		},
		icons = {
			["backpack-2"] = "rbxassetid://15653967858",
			["box-arrow-in-right"] = "rbxassetid://15646691259",
			["cart-4"] = "rbxassetid://15653968006",
			["plus-lg"] = "rbxassetid://15646533091",
		},
	},
}